### ISSUE TITLE
Error while loading checkpoint

### ISSUE THREAD

**Issue by philipperemy** [darkonhub/darkon-examples#1]
I have a pretty nasty error when I run the influence_cifar10_resnet code.

Can you guys check the content of the checkpoint? I didn't train the model before. I think I'm using the checkpoints you guys uploaded.

`darkon-examples/cifar10-resnet % python3 darkon_example.py`

Where `darkon_example.py` refers to `https://github.com/darkonhub/darkon-examples/blob/master/cifar10-resnet/influence_cifar10_resnet.ipynb`.

```
Reading images from cifar10_data/cifar-10-batches-py/data_batch_1
Reading images from cifar10_data/cifar-10-batches-py/data_batch_2
Reading images from cifar10_data/cifar-10-batches-py/data_batch_3
Reading images from cifar10_data/cifar-10-batches-py/data_batch_4
Reading images from cifar10_data/cifar-10-batches-py/data_batch_5
Reading images from cifar10_data/cifar-10-batches-py/test_batch

[...]

2018-01-10 15:50:00.462212: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key truediv/ExponentialMovingAverage not found in checkpoint
2018-01-10 15:50:00.462851: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key truediv/ExponentialMovingAverage not found in checkpoint
```

```
NotFoundError (see above for traceback): Key truediv/ExponentialMovingAverage not found in checkpoint
	 [[Node: save/RestoreV2_194 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_194/tensor_names, save/RestoreV2_194/shape_and_slices)]]
```

**Comment by zironycho** [comment]
Hi Philipperemy.
Thank you for reporting the issue to us. 
I made this example on `python2`, and it was working. However I didn't check on `python3` yet. I will test & update soon.

**Comment by zironycho** [comment]
I restored pre-trained model from 6e64951 commit. Please pull `darkon-examples's master` branch and run your darkon_example.py.

**Comment by philipperemy** [comment]
Thank you
